// Writes dist/sw.js after `vite build`: the app shell's file list, versioned by its contents.
//
// - Page loads: network first, cached shell when offline.
// - Same-origin static files: cache first (Vite hashes their names, so they never go stale).
// - Never touched: other origins (Supabase data, /ingest, /share), and embed.js, which host pages
//   load and must always get fresh.
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const DIST = 'dist';
const SKIP = new Set(['sw.js', 'embed.js', '404.html']);

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    return statSync(path).isDirectory() ? walk(path) : [path];
  });
}

const files = walk(DIST)
  .map((p) => relative(DIST, p).split('\\').join('/'))
  .filter((p) => !SKIP.has(p) && !p.endsWith('.map'))
  .sort();
const hash = createHash('sha256');
for (const f of files) hash.update(f).update(readFileSync(join(DIST, f)));
const version = hash.digest('hex').slice(0, 12);

const sw = `// Generated by scripts/build-sw.mjs. Don't edit.
const CACHE = 'habits-${version}';
const SHELL = ${JSON.stringify(['./', ...files], null, 2)};
const NO_CACHE = ['embed.js', 'sw.js'];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('habits-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  const url = new URL(req.url);
  if (req.method !== 'GET' || url.origin !== self.location.origin) return;
  if (NO_CACHE.some((f) => url.pathname.endsWith('/' + f))) return;

  if (req.mode === 'navigate') {
    // Fresh when online; the cached page of the same name (or the app) when not.
    event.respondWith(
      fetch(req).catch(async () => {
        const cache = await caches.open(CACHE);
        const page = url.pathname.endsWith('/embed.html') ? 'embed.html' : 'index.html';
        return (
          (await cache.match(page, { ignoreVary: true })) ??
          (await cache.match('./', { ignoreVary: true })) ??
          Response.error()
        );
      }),
    );
    return;
  }

  // ignoreVary: module scripts are requested with an Origin header that the cached copies (fetched
  // at install) didn't have, and servers may send Vary: Origin.
  event.respondWith(caches.match(req, { ignoreVary: true }).then((hit) => hit ?? fetch(req)));
});
`;
writeFileSync(join(DIST, 'sw.js'), sw);
console.log(`dist/sw.js: ${files.length} files, version ${version}`);
